DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER
(
    USER_ID         INT AUTO_INCREMENT NOT NULL,
    USER_LOGIN_ID   VARCHAR(20) NOT NULL,
    USER_ROLE       VARCHAR(20) DEFAULT 'ROLE_MEMBER' NOT NULL,
    USER_NAME       VARCHAR(20) NOT NULL,
    USER_PASSWD     VARCHAR(400) NOT NULL,
    USER_EMAIL      VARCHAR(100) NOT NULL,
    IS_USED         CHAR(1) DEFAULT 'Y' NOT NULL,
    IS_DEL          CHAR(1) DEFAULT 'N' NOT NULL,
    ISRT_DATE       DATETIME DEFAULT NOW() NOT NULL,
    UPDT_DATE       DATETIME ,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

-- 비밀번호 1111
INSERT INTO TB_USER (USER_LOGIN_ID, USER_NAME, USER_PASSWORD, USER_EMAIL)
VALUES ('member1', '전남혁', '$2a$12$umem9giXuB0lDzAQ1ofzmeVqwHHFX76sbMObVEWpcIOPc6O.47NGa', 'all_step@naver.com');

-- 비밀번호 1234
INSERT INTO TB_USER (USER_LOGIN_ID, USER_NAME, USER_PASSWORD, USER_EMAIL)
VALUES ('member2', '김철수', '$2a$12$R0ZgpAnBKh8CX0sATNRY8OyXPfke6GsXOxOA18gWyJ7RrnzOGnDOu', '');